services:
  backend:
    build:
      context: ./backend
    image: shop_itam:0.0.2
    container_name: backend
    environment:
      - BASIC_SERVER_PORT=8080
    ports:
      - "8080:8080"
  
  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"