FROM golang:1.23 AS builder
WORKDIR /app
COPY ./go.mod ./go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o /app/backend ./cmd/main.go

FROM ubuntu:22.04

RUN mkdir /app
WORKDIR /app

COPY --from=builder /app/backend .
RUN chmod -R +x .

ENTRYPOINT ["/app/backend"]